apiVersion: v2
description: IPerf3 server to benchmark kubernetes networking
name: iperf3
home: https://iperf.fr/iperf-download.php
version: 0.2.1
appVersion: 3.0.0
keywords:
  - benchmark
  - network
  - tools
sources:
  - https://github.com/EugenMayer/helm-charts/tree/main/charts/iperf3


# apiVersion: v2
# name: iperf3
# description: A Helm chart for Kubernetes

# # A chart can be either an 'application' or a 'library' chart.
# #
# # Application charts are a collection of templates that can be packaged into versioned archives
# # to be deployed.
# #
# # Library charts provide useful utilities or functions for the chart developer. They're included as
# # a dependency of application charts to inject those utilities and functions into the rendering
# # pipeline. Library charts do not define any templates and therefore cannot be deployed.
# type: application

# # This is the chart version. This version number should be incremented each time you make changes
# # to the chart and its templates, including the app version.
# # Versions are expected to follow Semantic Versioning (https://semver.org/)
# version: 0.0.1

# # This is the version number of the application being deployed. This version number should be
# # incremented each time you make changes to the application. Versions are not expected to
# # follow Semantic Versioning. They should reflect the version the application is using.
# # It is recommended to use it with quotes.
# appVersion: "3.0.0"
